move pre-build checks to separate file, add a pre-build summary job to convert skipped to success

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -83,90 +83,56 @@ jobs:
             - '.github/scripts/install_deps.sh' # calls install-dependencies.sh
             - '.github/workflows/build_appimage.yaml'
 
-  # This job runs multiple smaller checks where having several jobs would be overkill.
-  misc_sanity_checks:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 1
-    - name: Validate JSON files
-      run: |
-        python3 utils/validate_json.py data/txts/
-        python3 utils/update_authors.py
-    - name: Check for missing copyright headers
-      run: |
-        pushd src
-        ../utils/find_missing_copyright_headers.sh
-        popd
-    - name: Check for superfluous includes and forward declarations
-      run: |
-        pushd src
-        ../utils/find_unused_includes.py
-        popd
+  pre-build_checks:
+    needs: [changes]
+    uses: ./.github/workflows/pre-build_checks.yaml
 
   codecheck:
     needs: [changes]
     if: needs.changes.outputs.codecheck == 'true'
     uses: ./.github/workflows/build_codecheck.yaml
 
-  documentation:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 1
-    - name: Installing python
-      uses: actions/setup-python@v4
-      with:
-        python-version: 3.x
-    - name: Generate documentation
-      run: |
-        cd doc/sphinx
-        pip install -r requirements.txt
-        mkdir source/_static
-        ./extract_rst.py
-        sphinx-build -W -b json -d build/doctrees source build/json
-
   clang_tidy:
     needs: [changes]
     if: needs.changes.outputs.clang_tidy == 'true'
     uses: ./.github/workflows/build_clang_tidy.yaml
 
-  lua_style:
-    runs-on: ubuntu-latest
+  # Dummy check for PRs that all required pre-build checks have either passed or were skipped
+  # (see https://github.com/actions/runner/issues/952 and https://github.com/orgs/community/discussions/9141)
+  pre-build_summary:
+    name: Pre-Build Checks Summary
+    needs: [changes, clang-tidy, codecheck, pre-build_checks]
+    if: always() # to check if dependencies have failed or passed
+    runs-on: "ubuntu-latest"
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 1
-    - name: Prepare documentation examples for parsing
+    - name: Check for failed jobs
+      if: >-
+        contains(needs.*.result, 'failure') ||
+        contains(needs.*.result, 'cancelled')
       run: |
-        pushd doc/sphinx
-        ./extract_rst.py
-        popd
-    - name: Run Lua style checker
-      run: ./utils/lua_style_checker.py
+        echo "A job failed or was cancelled!"
+        exit 1
+    - name: No step skipped  # Optional, just gives info
+      if: "! contains(needs.*.result, 'skipped')"
+      run: true
 
   testsuite:
-    needs: [changes, clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
+    needs: [changes, pre-build_summary]
     if: needs.changes.outputs.run_test_suite == 'true'
     uses: ./.github/workflows/build_testsuite.yaml
 
   windows-msvc:
-    needs: [changes, clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
+    needs: [changes, pre-build_summary]
     if: needs.changes.outputs.inst_windows_msvc == 'true'
     uses: ./.github/workflows/build_windows_msvc.yaml
 
   windows:
-    needs: [changes, clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
+    needs: [changes, pre-build_summary]
     if: needs.changes.outputs.inst_windows == 'true'
     uses: ./.github/workflows/build_windows.yaml
 
   macos:
-    needs: [changes, clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
+    needs: [changes, pre-build_summary]
     if: needs.changes.outputs.inst_macos == 'true'
     uses: ./.github/workflows/build_macos.yaml
 
@@ -174,7 +140,7 @@ jobs:
     if: >
       github.repository == 'widelands/widelands' && github.ref == 'refs/heads/master' &&
       needs.changes.outputs.appimage == 'true'
-    needs: [changes, clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
+    needs: [changes, pre-build_summary]
     uses: ./.github/workflows/build_appimage.yaml
 
   # Dummy check for PRs that all required status checks have either passed or were skipped
