build_codecheck.yaml runs codecheck without cmake
All files are checked anyway. Using cmake is no advantage.
CodeCheck.py produces output for failures only, resulting in nicer output.

This spares to install dependencies, making the run about 20sec faster.

diff --git a/.github/workflows/build_codecheck.yaml b/.github/workflows/build_codecheck.yaml
--- a/.github/workflows/build_codecheck.yaml
+++ b/.github/workflows/build_codecheck.yaml
@@ -10,20 +10,21 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 1
-    - name: Installing dependencies
-      run: sh ./.github/scripts/install_deps.sh
     - name: Test
       run: |
         ./cmake/codecheck/run_tests.py
     - name: Check
       run: |
-        mkdir build
-        cd build
-        cmake .. -DCMAKE_BUILD_TYPE:STRING="Debug"
-        TERM=dumb make -j1 codecheck 2>&1 | tee codecheck.out
+        set -o pipefail # to keep return value
+        #
+        # for all c++ source files excluding /third_party/
+        ./cmake/codecheck/CodeCheck.py src/*.cc src/*.h src/[^t][^h]*/ |
+          tee codecheck.out
+        # exit code of CodeCheck.py is also 0 if failures detected
+      timeout-minutes: 2
     - name: Report
       run: |
-        if grep '^[/_.a-zA-Z]\+:[0-9]\+:' build/codecheck.out; then
+        if [ -s codecheck.out ] ; then
           echo "You have codecheck warnings (see above). Please fix."
           exit 1
         else
