Another try

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -15,11 +15,11 @@ jobs:
           - Release
           - Debug
         compiler:
-          - clang++-10
-          - clang++-9
-          - clang++-8
-          - clang++-7
-          - clang++-6.0
+          - clang-10
+          - clang-9
+          - clang-8
+          - clang-7
+          - clang-6.0
           - g++-10
           - g++-9
           - g++-8
@@ -38,14 +38,16 @@ jobs:
         fetch-depth: 1
     - name: Check
       run: |
-        if [[ ${{ matrix.compiler }} =~ clang* ]]
+        CXX=${{ matrix.compiler }}
+        if [ ${CXX:0:1} == c ]
         then
-          export CXX=/usr/bin/${{ matrix.compiler }}  # clang++-10
-          export CXX="${CC/++/}                       # clang-10
+          export CC="/usr/bin/${{ matrix.compiler }}"  # clang-10
+          export CXX="${CC/clang/clang++}              # clang++-10
         else
-          export CXX=/usr/bin/${{ matrix.compiler }} # g++-10
-          export CC="${CXX/g++/gcc}                  # gcc-10
+          export CXX="/usr/bin/${{ matrix.compiler }}" # g++-10
+          export CC="${CXX/g++/gcc}                    # gcc-10
         fi
+        echo "NOCOM '$CXX' '$CC'"
         mkdir build
         pushd build
         cmake .. -DCMAKE_BUILD_TYPE:STRING="${{ matrix.config }}" -DOPTION_BUILD_TRANSLATIONS="ON" -DOPTION_BUILD_WEBSITE_TOOLS="ON" -DOPTION_ASAN="OFF" -DOPTION_BUILD_CODECHECK="OFF"
@@ -56,22 +58,24 @@ jobs:
         export SDL_VIDEODRIVER=x11
         export DISPLAY=:99.0
         # Ignore transient SDL errors
-        trap 'err_handler' ERR
+        trap 'err_handler' EXIT
         err_handler() {
           result=$?
-          if [ $result -eq 2 ] ; then
-            echo "SDL initialization failed. TEST SKIPPED.";
-          else
-            # Exit with this error
+          if [ $result -eq 2 ]
+          then
+            echo "SDL initialization failed. TEST SKIPPED."
+          elif [ $result -ne 0 ]
+          then
+            echo "ERROR: $result"
             exit $result
           fi
         }
+        # Testsuite
+        ./regression_test.py -b build/src/widelands
         # Test website utils
         mkdir temp_web
         build/src/website/wl_map_object_info temp_web
         build/src/website/wl_map_info data/maps/Archipelago_Sea.wmf
-        # Testsuite
-        ./regression_test.py -b build/src/widelands
 
   includes:
     runs-on: ubuntu-latest
@@ -88,6 +92,10 @@ jobs:
   codecheck:
     runs-on: ubuntu-latest
     steps:
+    - name: Installing dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install cmake g++ gcc gettext libboost-dev libboost-regex-dev libboost-system-dev libboost-test-dev libglew-dev libpng-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev python zlib1g-dev clang-tidy -y
     - name: Checkout
       uses: actions/checkout@v2
       with:
@@ -113,9 +121,14 @@ jobs:
       uses: actions/checkout@v2
       with:
         fetch-depth: 1
+    - name: Installing python
+      uses: actions/setup-python@v1
+      with:
+        python-version: 3.x
     - name: Generate documentation
       run: |
-        cd ../doc/sphinx
+        pip install sphinx
+        cd doc/sphinx
         mkdir source/_static
         ./extract_rst.py
         sphinx-build -W -b json -d build/doctrees source build/json
