Change %u to %zu in 2 places as requested by Thomas R. - dtrauma in a comment to bug #1812008. Introduce the macro upcast to make upcasting a lot less verbose and repetitive. Use it in many places. Replace an ugly piece of code in game_debug_ui.cc using a switch and a lot of get_type cruft with a set of proper virtual functions (BaseImmovable::name and overriding versions in derived types). Improve the the detection of spurious source code and clean up everything that it finds (mostly old-style casts). Use initializer list for Network_Buffer. Rewrite erroneous loading code in widelands_map_battle_data_packet.cc. In the maps; fix some strings that had been saved in localized form, update packet formats and remove redundant (second) newlines at ends of files.
git-svn-id: https://widelands.svn.sourceforge.net/svnroot/widelands/trunk@2835 37b2a8de-5219-0410-9f54-a31bc463ab9c

diff --git a/utils/spurious_source_code/regexps/test b/utils/spurious_source_code/regexps/test
--- a/utils/spurious_source_code/regexps/test
+++ b/utils/spurious_source_code/regexps/test
@@ -1,21 +1,23 @@
 #! /bin/bash
 
-declare -i RESULT=0
+declare -i TESTS=0
+declare -i ERRORS=0
 for TEST in *; do
 	if [ -d $TEST ]; then
 		[[ -f $TEST/forbidden ]] && if [ "$(egrep -f $TEST/regexps $TEST/forbidden | wc -l)" != "$(wc -l < $TEST/forbidden)" ]; then
 			echo "$TEST failed to match all forbidden cases"
-			RESULT+=1
+			ERRORS+=1
 		fi
 		[[ -f $TEST/forbidden ]] && if [ "$(egrep -f $TEST/regexps $TEST/allowed | wc -l)" != "0" ]; then
 			echo "$TEST detected an allowed case as forbidden"
-			RESULT+=1
+			ERRORS+=1
 		fi
+		TESTS+=1
 	fi
 done
-if [ $RESULT == 0 ]; then
-	echo "All regexps passed their tests"
+if [ $ERRORS == 0 ]; then
+	echo "All $TESTS rules passed their tests"
 else
-	echo "$RESULT errors were found during the regexp tests"
+	echo "$ERRORS errors were found during the rule tests"
 fi
-exit $RESULT
+exit $ERRORS
